<?xml version="1.0" encoding="utf-8"?><Database Name="eWallet" Class="SqlDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.85.128;Initial Catalog=eWallet;Persist Security Info=True;User ID=sa" SettingsObjectName="eWallet.Data.Properties.Settings" SettingsPropertyName="eWalletConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.service_provider" Member="service_providers">
    <Type Name="service_provider">
      <Column Name="id" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="service" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="query_type" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="payment_type" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="service_service_provider" Member="service1" ThisKey="service" OtherKey="id" Type="service" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.branch" Member="branches">
    <Type Name="branch">
      <Column Name="id" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="address1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="address2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="district_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="provine_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Association Name="branch_finance_account" Member="finance_accounts" ThisKey="id" OtherKey="branch" Type="finance_account" />
      <Association Name="branch_finance_transaction" Member="finance_transactions" ThisKey="id" OtherKey="branch" Type="finance_transaction" />
      <Association Name="branch_profile" Member="profiles" ThisKey="id" OtherKey="branch" Type="profile" />
    </Type>
  </Table>
  <Table Name="dbo.finance_account" Member="finance_accounts">
    <Type Name="finance_account">
      <Column Name="id" Type="System.String" DbType="VarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="account_category" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="branch" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="current_balance" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="credit_today" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="debit_today" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="credit_current_month" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="debit_current_month" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="finance_account_finance_transaction_detail" Member="finance_transaction_details" ThisKey="id" OtherKey="account" Type="finance_transaction_detail" />
      <Association Name="finance_account_profile" Member="profiles" ThisKey="id" OtherKey="finance_account" Type="profile" />
      <Association Name="branch_finance_account" Member="branch1" ThisKey="branch" OtherKey="id" Type="branch" IsForeignKey="true" />
      <Association Name="finance_account_category_finance_account" Member="finance_account_category" ThisKey="account_category" OtherKey="id" Type="finance_account_category" IsForeignKey="true" />
      <Association Name="finance_account_category_finance_account1" Member="finance_account_category1" ThisKey="account_category" OtherKey="id" Type="finance_account_category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.finance_account_category" Member="finance_account_categories">
    <Type Name="finance_account_category">
      <Column Name="id" Type="System.String" DbType="VarChar(12) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="finance_account_category_finance_account" Member="finance_accounts" ThisKey="id" OtherKey="account_category" Type="finance_account" />
      <Association Name="finance_account_category_finance_account1" Member="finance_accounts1" ThisKey="id" OtherKey="account_category" Type="finance_account" />
    </Type>
  </Table>
  <Table Name="dbo.finance_account_currency" Member="finance_account_currencies">
    <Type Name="finance_account_currency">
      <Column Name="id" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.finance_account_roles" Member="finance_account_roles">
    <Type Name="finance_account_role">
      <Column Name="id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="operator" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="seq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="actived_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="created_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="created_by" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.finance_transaction" Member="finance_transactions">
    <Type Name="finance_transaction">
      <Column Name="id" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="reference_id" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="transaction_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="branch" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="transaction_code" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="allow_reverse" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="day_period" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="month_period" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="year_period" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Association Name="finance_transaction_finance_transaction_detail" Member="finance_transaction_details" ThisKey="id" OtherKey="parent_id" Type="finance_transaction_detail" />
      <Association Name="branch_finance_transaction" Member="branch1" ThisKey="branch" OtherKey="id" Type="branch" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.finance_transaction_detail" Member="finance_transaction_details">
    <Type Name="finance_transaction_detail">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="parent_id" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="debit" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="credit" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="balance_available" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="transaction_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Association Name="finance_transaction_finance_transaction_detail" Member="finance_transaction" ThisKey="parent_id" OtherKey="id" Type="finance_transaction" IsForeignKey="true" />
      <Association Name="finance_account_finance_transaction_detail" Member="finance_account" ThisKey="account" OtherKey="id" Type="finance_account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.profile" Member="profiles">
    <Type Name="profile">
      <Column Name="id" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="branch" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="profile_type" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="finance_account" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="mobile" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cert_id_number" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="cert_id_issuer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cert_id_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="cert_id_type" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="language" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="created_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_updated_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_updated_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="branch_profile" Member="branch1" ThisKey="branch" OtherKey="id" Type="branch" IsForeignKey="true" />
      <Association Name="finance_account_profile" Member="finance_account1" ThisKey="finance_account" OtherKey="id" Type="finance_account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.service" Member="services">
    <Type Name="service">
      <Column Name="id" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="service_service_provider" Member="service_providers" ThisKey="id" OtherKey="service" Type="service_provider" />
    </Type>
  </Table>
</Database>